
[project]
name = "NFLStudio"
version= "1.0.0"

dependencies = [
]

[tool.setuptools.packages.find]
include = ["NFLStudio*", "NFLStudio.lidarsim*"]

[project.entry-points.'nerfstudio.method_configs']
my-method = 'NFLStudio.my_config:NFLStudio'